name: README with GitHub Activity

on:
  schedule:
    - cron: "0 * * * *" # Every hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jamesgeorge007/github-activity-readme@master
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
